cc_library(
    name = "elf64",
    srcs = [
        "include/compiler.h",
        "include/config.h",
        "src/elf64.c",
        "src/elf64.h",
        "src/elfxx.h",
        "include/libunwind_i.h",
        "include/mempool.h",
        "include/dwarf.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "src/elfxx.c",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    deps = [
        "@lzma",
    ],
)

cc_library(
    name = "unwind-coredump",
    srcs = [
        "include/config.h",
        "src/coredump/_UCD_access_mem.c",
        "src/coredump/_UCD_access_reg_linux.c",
        "src/coredump/_UCD_accessors.c",
        "src/coredump/_UCD_corefile_elf.c",
        "src/coredump/_UCD_create.c",
        "src/coredump/_UCD_destroy.c",
        "src/coredump/_UCD_elf_map_image.c",
        "src/coredump/_UCD_find_proc_info.c",
        "src/coredump/_UCD_get_mapinfo_linux.c",
        "src/coredump/_UCD_get_proc_name.c",
        "src/coredump/_UCD_get_threadinfo_prstatus.c",
        "src/coredump/_UCD_internal.h",
        "src/coredump/_UCD_lib.h",
        "src/coredump/_UPT_access_fpreg.c",
        "src/coredump/_UPT_elf.c",
        "src/coredump/_UPT_get_dyn_info_list_addr.c",
        "src/coredump/_UPT_put_unwind_info.c",
        "src/coredump/_UPT_resume.c",
        "src/coredump/ucd_file_table.c",
        "src/coredump/ucd_file_table.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-coredump.h",
        "include/libunwind-dynamic.h",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
    ],
)

cc_library(
    name = "unwind-dwarf-common",
    srcs = [
        "include/dwarf_i.h",
        "include/dwarf.h",
        "include/libunwind_i.h",
        "include/config.h",
        "src/dwarf/global.c",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/libunwind-x86_64.h",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
    ],
)

cc_library(
    name = "unwind-dwarf-generic",
    srcs = [
        "include/dwarf-eh.h",
        "include/dwarf_i.h",
        "include/dwarf.h",
        "include/libunwind_i.h",
        "include/config.h",
        "src/dwarf/Gexpr.c",
        "src/dwarf/Gfde.c",
        "src/dwarf/Gfind_unwind_table.c",
        "src/dwarf/Gfind_proc_info-lsb.c",
        "src/dwarf/Gparser.c",
        "src/dwarf/Gpe.c",
        "src/os-linux.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/libunwind-x86_64.h",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "external/zlib",
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
        ":unwind-dwarf-common",
        "@zlib",
    ],
)

cc_library(
    name = "unwind-dwarf-local",
    srcs = [
        "include/dwarf-eh.h",
        "include/config.h",
        "src/dwarf/Lexpr.c",
        "src/dwarf/Lfde.c",
        "src/dwarf/Lfind_unwind_table.c",
        "src/dwarf/Lfind_proc_info-lsb.c",
        "src/dwarf/Lparser.c",
        "src/dwarf/Lpe.c",
        "src/os-linux.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/libunwind-x86_64.h",
        "src/dwarf/Gexpr.c",
        "src/dwarf/Gfde.c",
        "src/dwarf/Gfind_proc_info-lsb.c",
        "src/dwarf/Gfind_unwind_table.c",
        "src/dwarf/Gparser.c",
        "src/dwarf/Gpe.c",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "external/zlib",
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
        ":unwind-dwarf-common",
        "@zlib",
    ],
)

cc_library(
    name = "unwind-ptrace",
    srcs = [
        "include/config.h",
        "src/ptrace/_UPT_elf.c",
        "src/ptrace/_UPT_accessors.c",
        "src/ptrace/_UPT_access_fpreg.c",
        "src/ptrace/_UPT_access_mem.c",
        "src/ptrace/_UPT_access_reg.c",
        "src/ptrace/_UPT_create.c",
        "src/ptrace/_UPT_destroy.c",
        "src/ptrace/_UPT_find_proc_info.c",
        "src/ptrace/_UPT_get_dyn_info_list_addr.c",
        "src/ptrace/_UPT_put_unwind_info.c",
        "src/ptrace/_UPT_get_proc_name.c",
        "src/ptrace/_UPT_reg_offset.c",
        "src/ptrace/_UPT_resume.c",
        "src/ptrace/_UPT_internal.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/libunwind-ptrace.h",
        "include/libunwind-x86_64.h",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
    ],
)

cc_library(
    name = "unwind-setjmp",
    srcs = [
        "include/config.h",
        "src/setjmp/longjmp.c",
        "src/setjmp/siglongjmp.c",
        "src/setjmp/setjmp_i.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/libunwind-x86_64.h",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
    ],
)

cc_library(
    name = "unwind-x86_64",
    srcs = [
        "src/dl-iterate-phdr.c",
        "src/mi/Gdestroy_addr_space.c",
        "src/mi/Gdyn-extract.c",
        "src/mi/Gdyn-remote.c",
        "src/mi/Gfind_dynamic_proc_info.c",
        "src/mi/Gget_accessors.c",
        "src/mi/Gget_fpreg.c",
        "src/mi/Gget_proc_info_by_ip.c",
        "src/mi/Gget_proc_info_in_range.c",
        "src/mi/Gget_proc_name.c",
        "src/mi/Gget_reg.c",
        "src/mi/Gput_dynamic_unwind_info.c",
        "src/mi/Gset_cache_size.c",
        "src/mi/Gset_caching_policy.c",
        "src/mi/Gset_fpreg.c",
        "src/mi/Gset_reg.c",
        "src/mi/flush_cache.c",
        "src/mi/init.c",
        "src/mi/mempool.c",
        "src/mi/strerror.c",
        "src/os-linux.c",
        "src/x86_64/Gapply_reg_state.c",
        "src/x86_64/Gcreate_addr_space.c",
        "src/x86_64/Gget_proc_info.c",
        "src/x86_64/Gget_save_loc.c",
        "src/x86_64/Gglobal.c",
        "src/x86_64/Ginit.c",
        "src/x86_64/Ginit_local.c",
        "src/x86_64/Ginit_remote.c",
        "src/x86_64/Gos-linux.c",
        "src/x86_64/Greg_states_iterate.c",
        "src/x86_64/Gregs.c",
        "src/x86_64/Gresume.c",
        "src/x86_64/Gstash_frame.c",
        "src/x86_64/Gstep.c",
        "src/x86_64/Gtrace.c",
        "src/x86_64/is_fpreg.c",
        "src/x86_64/regname.c",
        "src/x86_64/unwind_i.h",
        "src/x86_64/ucontext_i.h",
        "src/x86_64/offsets.h",
        "src/x86_64/init.h",
        "include/remote.h",
        "src/os-linux.h",
        "include/dwarf_i.h",
        "include/dwarf-eh.h",
    ] + glob([
        "include/tdep-x86_64/*.h",
        "include/tdep/*.h",
    ]),
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/libunwind-x86_64.h",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
    ],
    alwayslink = True,
)

cc_library(
    name = "unwind",
    srcs = [
        "include/remote.h",
        "src/dl-iterate-phdr.c",
        "src/mi/Ldestroy_addr_space.c",
        "src/mi/Ldyn-extract.c",
        "src/mi/Lfind_dynamic_proc_info.c",
        "src/mi/Lget_accessors.c",
        "src/mi/Lget_fpreg.c",
        "src/mi/Lget_proc_info_by_ip.c",
        "src/mi/Lget_proc_info_in_range.c",
        "src/mi/Lget_proc_name.c",
        "src/mi/Lget_reg.c",
        "src/mi/Lput_dynamic_unwind_info.c",
        "src/mi/Lset_cache_size.c",
        "src/mi/Lset_caching_policy.c",
        "src/mi/Lset_fpreg.c",
        "src/mi/Lset_reg.c",
        "src/mi/backtrace.c",
        "src/mi/dyn-cancel.c",
        "src/mi/dyn-info-list.c",
        "src/mi/dyn-register.c",
        "src/mi/flush_cache.c",
        "src/mi/init.c",
        "src/mi/mempool.c",
        "src/mi/strerror.c",
        "src/os-linux.c",
        "src/x86_64/Lapply_reg_state.c",
        "src/x86_64/Lcreate_addr_space.c",
        "src/x86_64/Lget_proc_info.c",
        "src/x86_64/Lget_save_loc.c",
        "src/x86_64/Lglobal.c",
        "src/x86_64/Linit.c",
        "src/x86_64/Linit_local.c",
        "src/x86_64/Linit_remote.c",
        "src/x86_64/Los-linux.c",
        "src/x86_64/Lreg_states_iterate.c",
        "src/x86_64/Lregs.c",
        "src/x86_64/Lresume.c",
        "src/x86_64/Lstash_frame.c",
        "src/x86_64/Lstep.c",
        "src/x86_64/Ltrace.c",
        "src/x86_64/getcontext.S",
        "src/x86_64/init.h",
        "src/x86_64/is_fpreg.c",
        "src/x86_64/longjmp.S",
        "src/x86_64/offsets.h",
        "src/x86_64/regname.c",
        "src/x86_64/setcontext.S",
        "src/x86_64/siglongjmp.S",
        "src/x86_64/ucontext_i.h",
        "src/x86_64/unwind_i.h",
    ],
    hdrs = [
        "include/libunwind.h",
        "include/libunwind-common.h",
        "include/libunwind-dynamic.h",
        "include/unwind.h",
        "src/mi/Gdestroy_addr_space.c",
        "src/mi/Gdyn-extract.c",
        "src/mi/Gfind_dynamic_proc_info.c",
        "src/mi/Gget_accessors.c",
        "src/mi/Gget_fpreg.c",
        "src/mi/Gget_proc_info_by_ip.c",
        "src/mi/Gget_proc_info_in_range.c",
        "src/mi/Gget_proc_name.c",
        "src/mi/Gget_reg.c",
        "src/mi/Gput_dynamic_unwind_info.c",
        "src/mi/Gset_cache_size.c",
        "src/mi/Gset_caching_policy.c",
        "src/mi/Gset_fpreg.c",
        "src/mi/Gset_reg.c",
        "src/x86_64/Gapply_reg_state.c",
        "src/x86_64/Gcreate_addr_space.c",
        "src/x86_64/Gget_proc_info.c",
        "src/x86_64/Gget_save_loc.c",
        "src/x86_64/Gglobal.c",
        "src/x86_64/Ginit.c",
        "src/x86_64/Ginit_local.c",
        "src/x86_64/Ginit_remote.c",
        "src/x86_64/Gos-linux.c",
        "src/x86_64/Greg_states_iterate.c",
        "src/x86_64/Gregs.c",
        "src/x86_64/Gresume.c",
        "src/x86_64/Gstash_frame.c",
        "src/x86_64/Gstep.c",
        "src/x86_64/Gtrace.c",
    ],
    copts = [
        "-fPIC",
        "-fexceptions",
        "-Wall",
        "-Wsign-compare",
        "-Wno-cpp",
    ],
    includes = [
        "include",
        "include/tdep-x86_64",
        "src",
        "src/mi",
        "src/x86_64",
    ],
    local_defines = [
        "HAVE_CONFIG_H",
        "_GNU_SOURCE",
        "NDEBUG",
        "__EXTENSIONS__",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":elf64",
        ":unwind-dwarf-local",
    ],
    alwayslink = True,
)
